language: go

go:
  - "1.11"

env:
  - GO_ENV=test

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database invitation_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/invitation

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get github.com/gobuffalo/suite
  - go get $(go list ./... | grep -v /vendor/)

script: buffalo test